workflows:
  sample-workflow:
    name: Codemagic MDFE Ditonton
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
#      - name: Run unit tests
#        script: ./gradlew test
#        test_report: app/build/**/*.xml
      - name: Build Android App Bundle
        working_directory: android
        script: ./gradlew bundleRelease
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: refactor/migration_movie_to_bloc
        - pattern: develop
          include: false
      cancel_previous_builds: true